In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [80]:
df = pd.read_csv('train.txt',sep = ';',header = None, names = ['text','emotion'] )

In [81]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [82]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [83]:
unique_emotion = df['emotion'].unique()
emotion_numbers = {}

i = 0
for emotion in unique_emotion:
  emotion_numbers[emotion] = i
  i +=1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [84]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [85]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [86]:
import  string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [87]:
df['text'] = df['text'].apply(remove_punc)

In [88]:
def remove_number(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new = new + i
  return new

df['text'] = df['text'].apply(remove_number)

In [89]:
def remove_emoji(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new = new + i
  return new

df['text'] = df['text'].apply(remove_emoji)

In [90]:
import nltk

In [91]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [92]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [93]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [94]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [95]:
def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if not  i in stop_words:
      cleaned.append(i)
  return ' '.join(cleaned)

df['text']  = df['text'].apply(remove)

In [96]:
df

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [97]:
from sklearn.model_selection import train_test_split

In [98]:
X_train, X_test, y_train, y_test = train_test_split(df['text'],df['emotion'], test_size=0.20, random_state=42)

In [99]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [100]:
bow_vectorizer = CountVectorizer()

In [101]:
x_train_bow = bow_vectorizer.fit_transform(X_train)
x_test_bow = bow_vectorizer.fit_transform(X_test)

In [102]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [103]:
nb_model = MultinomialNB()

In [104]:
nb_model.fit(x_train_bow,y_trian)

MultinomialNB()

In [106]:
pred_nb = nb_model.predict(x_test_bow)
print(accuracy_score(y_test,pred_nb))

ValueError: X has 6175 features, but MultinomialNB is expecting 13361 features as input.

In [108]:
tfidf_vectorizer = TfidfVectorizer()

x_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
x_test_tfidf = tfidf_vectorizer.fit_transform(X_test)

In [109]:
nb2_model = MultinomialNB()
nb2_model.fit(x_train_bow,y_trian)

MultinomialNB()

In [110]:
pred_nb = nb2_model.predict(x_test_bow)
print(accuracy_score(y_test,pred_nb))

ValueError: X has 6175 features, but MultinomialNB is expecting 13361 features as input.