In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv(r"/content/anime.csv")

In [6]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [9]:
df.loc[3]['Title']

'Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'

In [20]:
def extract_episodes(txt):
  check = False
  data = ""
  for i in txt:

    if i == ')':
      break

    if i == '(':
      check = True
      continue

    if check == True:
      data += i
  return data

In [22]:
df['Episodes'] = df['Title'].apply(extract_episodes)

In [25]:
df['Episodes']=df['Episodes'].str.replace(" eps","")

In [27]:
df['Episodes'] = df['Episodes'].astype(int)

In [28]:
df

    Rank                                              Title  Score  Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04        51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04         1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04       148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04        13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03        13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03         2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02       110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99        13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99        13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98        12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94       201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94         1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93        22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93        24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91        25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91         1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89         1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88         7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88        14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87        74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84         1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84         1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83        12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83         1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82        24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82        23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81        12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81        26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80        13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80        16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79        11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79         1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79        11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78        10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78         1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77        26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77        12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76        75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75        26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75        26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74        24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73        10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72        12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71        12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71         4

In [30]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [36]:
def extraction_time(txt):
  data = ""
  for i in range(len(txt)):
    if txt[i] == ')':
      for j in range(i+1,i+20):
        data += txt[j]
      return data

In [38]:
df['Total Time']=df['Title'].apply(extraction_time)

In [39]:
df

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999

In [43]:
df[['Start', 'End']] = df['Total Time'].str.split(' - ', expand=True)

# convert to datetime
df['Start'] = pd.to_datetime(df['Start'], format='%b %Y')
df['End'] = pd.to_datetime(df['End'], format='%b %Y')

# calculate total months
df['Months'] = (df['End'].dt.year - df['Start'].dt.year) * 12 + \
                     (df['End'].dt.month - df['Start'].dt.month)

In [44]:
df

,Rank,Title,Score,Episodes,Total Time,start,end,months,Start,End,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,Apr 2009,Jul 2010,15,2009-04-01,2010-07-01,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,Apr 2011,Sep 2011,5,2011-04-01,2011-09-01,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,Oct 2022,Dec 2022,2,2022-10-01,2022-12-01,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,Apr 2015,Mar 2016,11,2015-04-01,2016-03-01,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,Apr 2019,Jul 2019,3,2019-04-01,2019-07-01,3
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012,Apr 2011,Mar 2012,11,2011-04-01,2012-03-01,11
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021,Jan 2021,Jan 2021,0,2021-01-01,2021-01-01,0
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,Oct 2011,Sep 2014,35,2011-10-01,2014-09-01,35
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022,Apr 2022,Jun 2022,2,2022-04-01,2022-06-01,2
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013,Oct 2012,Mar 2013,5,2012-10-01,2013-03-01,5
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023,Mar 2023,May 2023,2,2023-03-01,2023-05-01,2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,Jan 1988,Mar 1997,110,1988-01-01,1997-03-01,110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023,Jul 2023,Aug 2023,1,2023-07-01,2023-08-01,1
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021,Apr 2021,Jun 2021,2,2021-04-01,2021-06-01,2
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017,Jan 2017,Mar 2017,2,2017-01-01,2017-03-01,2
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,Apr 2006,Mar 2010,47,2006-04-01,2010-03-01,47
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016,Sep 2016,Sep 2016,0,2016-09-01,2016-09-01,0
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018,Oct 2017,Mar 2018,5,2017-10-01,2018-03-01,5
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009,Oct 2008,Mar 2009,5,2008-10-01,2009-03-01,5
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008,Apr 2008,Sep 2008,5,2008-04-01,2008-09-01,5
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013,Jul 2013,Jul 2013,0,2013-07-01,2013-07-01,0
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020,Sep 2020,Sep 2020,0,2020-09-01,2020-09-01,0
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017,Aug 2017,Aug 2017,0,2017-08-01,2017-08-01,0
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018,Jul 2018,Oct 2018,3,2018-07-01,2018-10-01,3
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,Apr 2004,Sep 2005,17,2004-04-01,2005-09-01,17
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016,Aug 2016,Aug 2016,0,2016-08-01,2016-08-01,0
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022,Dec 2022,Dec 2022,0,2022-12-01,2022-12-01,0
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022,Oct 2022,Dec 2022,2,2022-10-01,2022-12-01,2
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022,Dec 2022,Dec 2022,0,2022-12-01,2022-12-01,0
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023,Jan 2023,Jun 2023,5,2023-01-01,2023-06-01,5
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023,Jul 2023,Aug 2023,1,2023-07-01,2023-08-01,1
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018,Jan 2018,Mar 2018,2,2018-01-01,2018-03-01,2
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021,Apr 2020,Oct 2021,18,2020-04-01,2021-10-01,18
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019,Jan 2019,Apr 2019,3,2019-01-01,2019-04-01,3
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021,Dec 2020,Mar 2021,3,2020-12-01,2021-03-01,3
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022,Dec 2021,Feb 2022,2,2021-12-01,2022-02-01,2
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017,Jan 2017,Jan 2017,0,2017-01-01,2017-01-01,0
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023,Apr 2023,Jun 2023,2,2023-04-01,2023-06-01,2
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016,Oct 2016,Dec 2016,2,2016-10-01,2016-12-01,2
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001,Jul 2001,Jul 2001,0,2001-07-01,2001-07-01,0
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013,Jul 2013,Dec 2013,5,2013-07-01,2013-12-01,5
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022,Jan 2022,Apr 2022,3,2022-01-01,2022-04-01,3
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,Oct 2000,Mar 2002,17,2000-10-01,2002-03-01,17
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999,Apr 1998,Apr 1999,12,1998-04-01,1999-04-01,12
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022,Apr 2022,Oct 2022,6,2022-04-01,2022-10-01,6
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019,Jul 2019,Dec 2019,5,2019-07-01,2019-12-01,5
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014,Oct 2014,Dec 2014,2,2014-10-01,2014-12-01,2
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017,Jan 2017,Mar 2017,2,2017-01-01,2017-03-01,2
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022,Oct 2022,Dec 2022,2,2022-10-01,2022-12-01,2
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999,Feb 1999,Sep 1999,7,1999-02-01,1999-09-01,7

In [47]:
# remove everything after TV/Movie/OVA/ONA
df['Title'] = df['Title'].str.replace(
    r'(TV|Movie|OVA|ONA).*', '', regex=True
)

# strip extra spaces
df['Title'] = df['Title'].str.strip()

In [48]:
df

,Rank,Title,Score,Episodes,Total Time,start,end,months,Start,End,Months
0,1,Fullmetal Alchemist: Brotherhood,9.10,64,Apr 2009 - Jul 2010,Apr 2009,Jul 2010,15,2009-04-01,2010-07-01,15
1,2,Steins;Gate,9.07,24,Apr 2011 - Sep 2011,Apr 2011,Sep 2011,5,2011-04-01,2011-09-01,5
2,3,Bleach: Sennen Kessen-hen,9.06,13,Oct 2022 - Dec 2022,Oct 2022,Dec 2022,2,2022-10-01,2022-12-01,2
3,4,Gintama°,9.06,51,Apr 2015 - Mar 2016,Apr 2015,Mar 2016,11,2015-04-01,2016-03-01,11
4,5,Shingeki no Kyojin Season 3 Part 2,9.05,10,Apr 2019 - Jul 2019,Apr 2019,Jul 2019,3,2019-04-01,2019-07-01,3
5,6,Gintama',9.04,51,Apr 2011 - Mar 2012,Apr 2011,Mar 2012,11,2011-04-01,2012-03-01,11
6,7,Gintama: The Final,9.04,1,Jan 2021 - Jan 2021,Jan 2021,Jan 2021,0,2021-01-01,2021-01-01,0
7,8,Hunter x Hunter,9.04,148,Oct 2011 - Sep 2014,Oct 2011,Sep 2014,35,2011-10-01,2014-09-01,35
8,9,Kaguya-sama wa Kokurasetai: Ultra Romantic,9.04,13,Apr 2022 - Jun 2022,Apr 2022,Jun 2022,2,2022-04-01,2022-06-01,2
9,10,Gintama': Enchousen,9.03,13,Oct 2012 - Mar 2013,Oct 2012,Mar 2013,5,2012-10-01,2013-03-01,5
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023,Mar 2023,May 2023,2,2023-03-01,2023-05-01,2
11,12,Ginga Eiyuu Densetsu,9.02,110,Jan 1988 - Mar 1997,Jan 1988,Mar 1997,110,1988-01-01,1997-03-01,110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tan,8.99,13,Jul 2023 - Aug 2023,Jul 2023,Aug 2023,1,2023-07-01,2023-08-01,1
13,14,Fruits Basket: The Final,8.99,13,Apr 2021 - Jun 2021,Apr 2021,Jun 2021,2,2021-04-01,2021-06-01,2
14,15,Gintama.,8.98,12,Jan 2017 - Mar 2017,Jan 2017,Mar 2017,2,2017-01-01,2017-03-01,2
15,16,Gintama,8.94,201,Apr 2006 - Mar 2010,Apr 2006,Mar 2010,47,2006-04-01,2010-03-01,47
16,17,Koe no Katachi,8.94,1,Sep 2016 - Sep 2016,Sep 2016,Sep 2016,0,2016-09-01,2016-09-01,0
17,18,3-gatsu no Lion 2nd Season,8.93,22,Oct 2017 - Mar 2018,Oct 2017,Mar 2018,5,2017-10-01,2018-03-01,5
18,19,Clannad: After Story,8.93,24,Oct 2008 - Mar 2009,Oct 2008,Mar 2009,5,2008-10-01,2009-03-01,5
19,20,Code Geass: Hangyaku no Lelouch R2,8.91,25,Apr 2008 - Sep 2008,Apr 2008,Sep 2008,5,2008-04-01,2008-09-01,5
20,21,Gintama,8.91,1,Jul 2013 - Jul 2013,Jul 2013,Jul 2013,0,2013-07-01,2013-07-01,0
21,22,Violet Evergarden,8.89,1,Sep 2020 - Sep 2020,Sep 2020,Sep 2020,0,2020-09-01,2020-09-01,0
22,23,Owarimonogatari 2nd Season,8.88,7,Aug 2017 - Aug 2017,Aug 2017,Aug 2017,0,2017-08-01,2017-08-01,0
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-sen,8.88,14,Jul 2018 - Oct 2018,Jul 2018,Oct 2018,3,2018-07-01,2018-10-01,3
24,25,Monster,8.87,74,Apr 2004 - Sep 2005,Apr 2004,Sep 2005,17,2004-04-01,2005-09-01,17
25,26,Kimi no Na wa.,8.84,1,Aug 2016 - Aug 2016,Aug 2016,Aug 2016,0,2016-08-01,2016-08-01,0
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022,Dec 2022,Dec 2022,0,2022-12-01,2022-12-01,0
27,28,Bocchi the Rock!,8.83,12,Oct 2022 - Dec 2022,Oct 2022,Dec 2022,2,2022-10-01,2022-12-01,2
28,29,The First Slam Dunk,8.83,1,Dec 2022 - Dec 2022,Dec 2022,Dec 2022,0,2022-12-01,2022-12-01,0
29,30,Vinland Saga Season 2,8.82,24,Jan 2023 - Jun 2023,Jan 2023,Jun 2023,5,2023-01-01,2023-06-01,5
30,31,Jujutsu Kaisen 2nd Season,8.82,23,Jul 2023 - Aug 2023,Jul 2023,Aug 2023,1,2023-07-01,2023-08-01,1
31,32,Gintama.: Shirogane no Tamashii-hen,8.81,12,Jan 2018 - Mar 2018,Jan 2018,Mar 2018,2,2018-01-01,2018-03-01,2
32,33,Kingdom 3rd Season,8.81,26,Apr 2020 - Oct 2021,Apr 2020,Oct 2021,18,2020-04-01,2021-10-01,18
33,34,Mob Psycho 100 II,8.80,13,Jan 2019 - Apr 2019,Jan 2019,Apr 2019,3,2019-01-01,2019-04-01,3
34,35,Shingeki no Kyojin: The Final Season,8.80,16,Dec 2020 - Mar 2021,Dec 2020,Mar 2021,3,2020-12-01,2021-03-01,3
35,36,Kimetsu no Yaiba: Yuukaku-hen,8.79,11,Dec 2021 - Feb 2022,Dec 2021,Feb 2022,2,2021-12-01,2022-02-01,2
36,37,Kizumonogatari III: Reiketsu-hen,8.79,1,Jan 2017 - Jan 2017,Jan 2017,Jan 2017,0,2017-01-01,2017-01-01,0
37,38,"""Oshi no Ko""",8.79,11,Apr 2023 - Jun 2023,Apr 2023,Jun 2023,2,2023-04-01,2023-06-01,2
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016,Oct 2016,Dec 2016,2,2016-10-01,2016-12-01,2
39,40,Sen to Chihiro no Kamikakushi,8.78,1,Jul 2001 - Jul 2001,Jul 2001,Jul 2001,0,2001-07-01,2001-07-01,0
40,41,Monogatari Series: Second Season,8.77,26,Jul 2013 - Dec 2013,Jul 2013,Dec 2013,5,2013-07-01,2013-12-01,5
41,42,Shingeki no Kyojin: The Final Season Part 2,8.77,12,Jan 2022 - Apr 2022,Jan 2022,Apr 2022,3,2022-01-01,2022-04-01,3
42,43,Hajime no Ippo,8.76,75,Oct 2000 - Mar 2002,Oct 2000,Mar 2002,17,2000-10-01,2002-03-01,17
43,44,Cowboy Bebop,8.75,26,Apr 1998 - Apr 1999,Apr 1998,Apr 1999,12,1998-04-01,1999-04-01,12
44,45,Kingdom 4th Season,8.75,26,Apr 2022 - Oct 2022,Apr 2022,Oct 2022,6,2022-04-01,2022-10-01,6
45,46,Vinland Saga,8.74,24,Jul 2019 - Dec 2019,Jul 2019,Dec 2019,5,2019-07-01,2019-12-01,5
46,47,Mushishi Zoku Shou 2nd Season,8.73,10,Oct 2014 - Dec 2014,Oct 2014,Dec 2014,2,2014-10-01,2014-12-01,2
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017,Jan 2017,Mar 2017,2,2017-01-01,2017-03-01,2
48,49,Mob Psycho 100 III,8.71,12,Oct 2022 - Dec 2022,Oct 2022,Dec 2022,2,2022-10-01,2022-12-01,2
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999,Feb 1999,Sep 1999,7,1999-02-01,1999-09-01,7

In [53]:
df[df['Score'] == df['Score'].max()]['Title']

0    Fullmetal Alchemist: Brotherhood
Name: Title, dtype: object

In [56]:
df['Title'].head()

0      Fullmetal Alchemist: Brotherhood
1                           Steins;Gate
2             Bleach: Sennen Kessen-hen
3                              Gintama°
4    Shingeki no Kyojin Season 3 Part 2
Name: Title, dtype: object