In [5]:
d = {
    'NAME': ['SATYAM','SOHAN','MANOH','DEEPAK'],
    'AGES': [22,12,13,14],
    'CITY': ['BHOPAL','INDORE','BHOPAL','BANGLORU'],
    'SALARY': [12,12,12,12]
}

In [6]:
import pandas as pd
import numpy as np

In [7]:
DF = pd.DataFrame(d)
DF

     NAME  AGES      CITY  SALARY
0  SATYAM    22    BHOPAL      12
1   SOHAN    12    INDORE      12
2   MANOH    13    BHOPAL      12
3  DEEPAK    14  BANGLORU      12

In [12]:
list = [
    ['SATYAM',22,'bhopal',34],
    ['SATYAM',22,'bhopal',34],
    ['SATYAM',22,'bhopal',34],
    ['SATYAM',22,'bhopal',34],
]

colum = ['name','age','locationn','salary']

df = pd.DataFrame(list, columns = colum)
df

     name  age locationn  salary
0  SATYAM   22    bhopal      34
1  SATYAM   22    bhopal      34
2  SATYAM   22    bhopal      34
3  SATYAM   22    bhopal      34

In [13]:
df1 = pd.DataFrame(list)
df1

        0   1       2   3
0  SATYAM  22  bhopal  34
1  SATYAM  22  bhopal  34
2  SATYAM  22  bhopal  34
3  SATYAM  22  bhopal  34

In [14]:
df['DAGIGNATION']= ['DOC','ENG','DOC','ENG']
df

     name  age locationn  salary DAGIGNATION
0  SATYAM   22    bhopal      34         DOC
1  SATYAM   22    bhopal      34         ENG
2  SATYAM   22    bhopal      34         DOC
3  SATYAM   22    bhopal      34         ENG

In [17]:
df.drop('DAGIGNATION', axis=1,inplace=True)

In [18]:
df

     name  age locationn  salary
0  SATYAM   22    bhopal      34
1  SATYAM   22    bhopal      34
2  SATYAM   22    bhopal      34
3  SATYAM   22    bhopal      34

In [19]:
df.drop(0,axis=0)

     name  age locationn  salary
1  SATYAM   22    bhopal      34
2  SATYAM   22    bhopal      34
3  SATYAM   22    bhopal      34

In [25]:
DF.loc[0]
DF

     NAME  AGES      CITY  SALARY
0  SATYAM    22    BHOPAL      12
1   SOHAN    12    INDORE      12
2   MANOH    13    BHOPAL      12
3  DEEPAK    14  BANGLORU      12

In [26]:
DF.loc[[0,1]][['CITY','SALARY']]

     CITY  SALARY
0  BHOPAL      12
1  INDORE      12